name: Build and Deploy App
on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the `main` branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Set image tag
        id: image_tag
        run: |
          echo "COMMIT_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-frontend:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "LATEST_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-frontend:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Building image with tags: $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"
          docker build -t $COMMIT_IMAGE_TAG -t $LATEST_IMAGE_TAG ./frontend
          echo "Built image with tags : $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"
  
      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing image: $COMMIT_IMAGE_TAG"
          docker push $COMMIT_IMAGE_TAG
          echo "Pushing image: $LATEST_IMAGE_TAG"
          docker push $LATEST_IMAGE_TAG

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_CLOUD_SA }}" > /tmp/gcloud-key.json
          gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reminder-frontend \
            --image $COMMIT_IMAGE_TAG \
            --platform managed \
            --region us-central1 \
            --port 8080 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --set-env-vars REACT_APP_API_URL=https://reminder-backend-349073578254.us-central1.run.app
  
  
  
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Set image tag
      id: image_tag
      run: |
        echo "COMMIT_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-backend:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        echo "LATEST_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-backend:latest" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        echo "Building image with tags: $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"
        docker build -t $COMMIT_IMAGE_TAG -t $LATEST_IMAGE_TAG ./backend
        echo "Built image with tags : $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"

    - name: Push Docker image to Docker Hub
      run: |
        echo "Pushing image: $COMMIT_IMAGE_TAG"
        docker push $COMMIT_IMAGE_TAG
        echo "Pushing image: $LATEST_IMAGE_TAG"
        docker push $LATEST_IMAGE_TAG

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_SA }}" > /tmp/gcloud-key.json
        gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy reminder-backend \
          --image $COMMIT_IMAGE_TAG \
          --platform managed \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-secrets="/app/.secrets/firebasekey.json=FIREBASE_KEY:latest" \
          --allow-unauthenticated