name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the `main` branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub using Personal Access Token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # The personal access token

    - name: Set image tag
      id: image_tag
      run: |
        echo "COMMIT_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-backend:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        echo "LATEST_IMAGE_TAG=docker.io/${{ secrets.DOCKER_USERNAME }}/reminder-backend:latest" >> $GITHUB_ENV

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        echo "Building image with tags: $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"
        docker build -t $COMMIT_IMAGE_TAG -t $LATEST_IMAGE_TAG .
        echo "Built image with tags : $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG"

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        echo "Pushing image: $COMMIT_IMAGE_TAG"
        docker push $COMMIT_IMAGE_TAG
        echo "Pushing image: $LATEST_IMAGE_TAG"
        docker push $LATEST_IMAGE_TAG

    # Step 6: Authenticate with Google Cloud using Service Account Key
    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_SA }}" > /tmp/gcloud-key.json
        gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 7: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy reminder-backend \
          --image $IMAGE_TAG \
          --platform managed \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-secrets="/app/.secrets/firebasekey.json=FIREBASE_KEY:latest" \
          --allow-unauthenticated
